export const MODELS = {
  CENTRAL_AFRICAN_FORESTS: {
    file: 'central_african_forests.onnx',
    name: 'Central African forests',
    labels: [
      'Bird',
      'Blank',
      'Buffalo_African',
      'Cat_Golden',
      'Chevrotain_Water',
      'Chimpanzee',
      'Civet_African_Palm',
      'Duiker_Blue',
      'Duiker_Red',
      'Duiker_Yellow_Backed',
      'Elephant_African',
      'Genet',
      'Gorilla',
      'Guineafowl_Black',
      'Guineafowl_Crested',
      'Hog_Red_River',
      'Human',
      'Leopard_African',
      'Mandrillus',
      'Mongoose',
      'Mongoose_Black_Footed',
      'Monkey',
      'Pangolin',
      'Porcupine_Brush_Tailed',
      'Rail_Nkulengu',
      'Rat_Giant',
      'Rodent',
      'Squirrel',
    ],
  },
  EAST_AFRICAN_SAVANNAS: {
    file: 'east_african_savannas.onnx',
    name: 'East African savannas',
    labels: [
      'aardvark',
      'aardwolf',
      'baboon',
      'bat',
      'batearedfox',
      'buffalo',
      'bushbuck',
      'caracal',
      'cattle',
      'cheetah',
      'civet',
      'dikdik',
      'duiker',
      'eland',
      'elephant',
      'empty',
      'gazellegrants',
      'gazellethomsons',
      'genet',
      'giraffe',
      'guineafowl',
      'hare',
      'hartebeest',
      'hippopotamus',
      'honeybadger',
      'hyenaspotted',
      'hyenastriped',
      'impala',
      'insectspider',
      'jackal',
      'koribustard',
      'leopard',
      'lionfemale',
      'lionmale',
      'mongoose',
      'monkeyvervet',
      'ostrich',
      'otherbird',
      'porcupine',
      'reedbuck',
      'reptiles',
      'rhinoceros',
      'rodents',
      'secretarybird',
      'serval',
      'steenbok',
      'topi',
      'vulture',
      'warthog',
      'waterbuck',
      'wildcat',
      'wildebeest',
      'zebra',
      'zorilla',
    ],
  },
};

export type Model = keyof typeof MODELS;
