export const MODELS = {
  GABON: {
    name: 'Central African forests (Gabon)',
    file: 'gabon.onnx',
    photoShape: { width: 768, height: 576 },
    labels: [
      'Bird',
      'Blank',
      'Buffalo_African',
      'Cat_Golden',
      'Chevrotain_Water',
      'Chimpanzee',
      'Civet_African_Palm',
      'Duiker_Blue',
      'Duiker_Red',
      'Duiker_Yellow_Backed',
      'Elephant_African',
      'Genet',
      'Gorilla',
      'Guineafowl_Black',
      'Guineafowl_Crested',
      'Hog_Red_River',
      'Human',
      'Leopard_African',
      'Mandrillus',
      'Mongoose',
      'Mongoose_Black_Footed',
      'Monkey',
      'Pangolin',
      'Porcupine_Brush_Tailed',
      'Rail_Nkulengu',
      'Rat_Giant',
      'Rodent',
      'Squirrel',
    ],
  },
  SERENGETI: {
    name: 'East African savannas (Serengeti)',
    file: 'serengeti.onnx',
    photoShape: { width: 512, height: 384 },
    labels: [
      'aardvark',
      'aardwolf',
      'baboon',
      'bat',
      'batearedfox',
      'buffalo',
      'bushbuck',
      'caracal',
      'cattle',
      'cheetah',
      'civet',
      'dikdik',
      'duiker',
      'eland',
      'elephant',
      'empty',
      'gazellegrants',
      'gazellethomsons',
      'genet',
      'giraffe',
      'guineafowl',
      'hare',
      'hartebeest',
      'hippopotamus',
      'honeybadger',
      'hyenaspotted',
      'hyenastriped',
      'impala',
      'insectspider',
      'jackal',
      'koribustard',
      'leopard',
      'lionfemale',
      'lionmale',
      'mongoose',
      'monkeyvervet',
      'ostrich',
      'otherbird',
      'porcupine',
      'reedbuck',
      'reptiles',
      'rhinoceros',
      'rodents',
      'secretarybird',
      'serval',
      'steenbok',
      'topi',
      'vulture',
      'warthog',
      'waterbuck',
      'wildcat',
      'wildebeest',
      'zebra',
      'zorilla',
    ],
  },
  OL_PEJETA: {
    name: 'East African savannas (Ol Pejeta Conservancy)',
    file: 'ol_pejeta.onnx',
    photoShape: { width: 480, height: 270 },
    labels: [
      'aardvark',
      'baboon',
      'bird',
      'buffalo',
      'cheetah',
      'duiker',
      'eland',
      'elephant',
      'giraffe',
      'grants_gazelle',
      'hare',
      'hartebeest',
      'honey_badger',
      'human_activity',
      'impala',
      'jackal',
      'kori_bustard',
      'leopard',
      'lion',
      'livestock',
      'oryx',
      'patas_monkey',
      'porcupine',
      'rhino',
      'spotted_hyena',
      'steinbuck',
      'striped_hyena',
      'thomson_gazelle',
      'warthog',
      'waterbuck',
      'wild_dog',
      'zebra',
    ],
  },
};

export type Model = keyof typeof MODELS;
