name: Test

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 13

      - name: yarn install
        run: |
          yarn install

      - name: yarn test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn ts

      - name: Archive packaged app artifact for MacOS
        uses: actions/upload-artifact@v1
        with:
          name: release/ElectronReact-1.0.0-mac.zip
          path: ElectronReact-1.0.0-mac.zip
        if: ${{ contains(matrix.os, 'macos'}}
# Failing beacuse virtual framebuffer not installed
#          yarn build-e2e
#          yarn test-e2e
